@startuml Booking(DELETE)
    header Dentist-Booking-System Sequence Diagram
    title "Booking(DELETE)"

    participant "Client" as client
    participant "<<javaScript>>\n:server" as server
    participant "<<router>>\n:bookings" as bookingRouter
    participant "<<middleware>>\n:auth" as authMiddleware
    participant "<<controllers>>\n:bookings" as bookingController
    participant "<<models>>\n:Booking" as bookingModel
    database "<<MongoDB>>\n:bookings" as bookingDatabase

    client -> server ++: req.delete('/bookings/:id')
    server -> bookingRouter ++: app.use('/bookings', bookings)
    bookingRouter ->> authMiddleware ++: protect(), authorize('admin', 'user')
    alt Not authorized
        authMiddleware ->> client --: Unauthorized or unprotected
    else Authorized
        authMiddleware ->> bookingRouter --: Authroized and protected
    bookingRouter -> bookingController ++: deleteBooking()
    bookingController -> bookingModel ++: findById(req.params.id)
    bookingModel -> bookingDatabase ++: bookingschema
    bookingModel <-- bookingDatabase --: booking
    bookingController <-- bookingModel --: booking
    client <-- bookingController --: response
    end
@enduml